---
title: "Confirmed Cases"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
# Covid Time Series
library(tidyverse)
library(lubridate)
library(zoo)
library(readr)

myfile <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
sample <- read.csv(myfile)
sample <- sample %>% group_by(Country.Region)
sample <- sample %>% summarise_if(is.numeric,sum)
sample <- sample %>% select(-2,-3) %>% pivot_longer(-Country.Region,names_to = "date", values_to = "confirmed")

sample$date <- as.character(sample$date)
sample$date <-str_sub(sample$date,2,8)
sample$date <- str_replace_all(sample$date, "[.]", "/")

# This snipt requires lubridate and zoo:
sample$date <- parse_date(sample$date, "%m/%d/%y")
sample$day <- as.numeric(format(sample$date,"%d"))
sample$month <- as.numeric(format(sample$date,"%m"))
sample$year <- as.numeric(format(sample$date,"%Y"))
#unique(sample$Country.Region)
```

### Chart A

```{r}
# Script to plot a selected country:
pais1 = "Chile"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart B

```{r}
# Script to plot a selected country:
pais1 = "Ukraine"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart C

```{r}
# Script to plot a selected country:
pais1 = "United Kingdom"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart D
```{r}
# Script to plot a selected country:
pais1 = "Italy"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart E
```{r}
# Script to plot a selected country:
pais1 = "China"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart F
```{r}
# Script to plot a selected country:
pais1 = "Spain"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```

### Chart G
```{r}
# Script to plot a selected country:
pais1 = "US"
pais <- sample %>% filter(Country.Region == pais1 & confirmed > 0) 
#pais <- pais %>% slice(1:15)
pais$days <- c(1:length(pais$date))
ggplot(pais, aes(days,confirmed)) + geom_col() + ggtitle(paste0(pais1,": Confirmed Cases after ",length(pais$date)," days\nHerman Aguirre-Jofre"))
```